### ISSUE TITLE
Text effects may be harmful to users with photosensitivity

### ISSUE THREAD

**Issue by t-m-w** [AndronixApp/andronix-website-base#24]
There's a significant amount of flickering/flashing caused by the text effects that occur when scrolling through the page. While some users may find it generally unpleasant or uncomfortable, others will find it painful, and those with more serious photosensitivity may even experience seizures as a result.

I'm not sure if this is related to #22, but in the event that this effect is intentional, here are some resources to consider reviewing:
- [Web accessibility for seizures and physical reactions - Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Seizure_disorders)
- [Three Flashes or Below Threshold - W3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html)
- [Flashing Content - Case Western Reserve University](https://case.edu/accessibility/what-accessibility/guidelines/flashing-content)
- [Photosensitive Epilepsy Analysis Tool (PEAT) - Trace Research & Development Center, University of Maryland](https://trace.umd.edu/peat/)

**Comment by MajesticTwelve12** [comment]
The website is unviewable to me. I just couldn't view it because how the text comes onto the screen.
This is unacceptable web design, and I agree with the issue here.

**Comment by jasons393** [comment]
It also looks pretty awful, and I agree that it can be pretty unpleasant looking at it. Please change it.

**Comment by imprakharshukla** [comment]
Thank you for bringing this up. It has been fixed now!
